### ISSUE TITLE
linux: Possible to flash firmware `*.ino` binaries with espressif tools  directly (or maybe via Arduino IDE)?

### ISSUE THREAD

**Issue by eacousineau** [elephantrobotics/myStudio#10]
From my read on the [arduino intro in the GitBooks](https://www.elephantrobotics.com/docs/myCobot-en/2-preparation/1-background_knowledge/arduino.html), it seems like the main control board (M5 Basic) could be flashed using the [`espressif` tools](https://github.com/espressif/arduino-esp32) directly, and maybe the sub-control board (M5 Atom) could be too - any chance y'all would be able to document this and kinda support it as a workflow?

I'd much prefer having open-source host-side tooling, especially if the core work may already be done using open source tools.
For the firmware, I see that the main M5 basic stuff is open-source, and I'm OK w/ the sub-control board not being open-source (though would love it did become open-source at some point :wink:).

FWIW I also dunno if the Arduino IDE could be used :shrug: 

Kinda relates #8

**Comment by zlj-zz** [comment]
What's your mean❓ Basic firmware source code, you can find here[https://github.com/elephantrobotics/myCobot/tree/main/Arduino/MycobotBasic/examples](https://github.com/elephantrobotics/myCobot/tree/main/Arduino/MycobotBasic/examples)

We use `esptool` to flash the `*.ino` binaries.

**Comment by eacousineau** [comment]
Thanks! (and sorry for delay!)

For the base of the robot, I see the source code; however, for the end-effector (which houses the control code), is it still possible to flash the proprietary firmware using `esptool` directly?

**Comment by zlj-zz** [comment]
Yes. The end is also burned with `esptool`.

**Comment by eacousineau** [comment]
Sweet! I just tried it out, but may not have the right configuration.

Here is what I tried on Ubuntu 18.04:
- Download [MyStudio 2.2](https://github.com/elephantrobotics/myStudio/releases/tag/v2.2)
  - Extract `*.ino` files to `~/Downloads/mystudio_2.2/ino/`
- Download [Arduino 1.8.15](https://downloads.arduino.cc/arduino-1.8.15-linux64.tar.xz)
  - Install prereqs for python2: `sudo apt install python-serial`
  - Install M5Stack dev software: [docs](https://docs.m5stack.com/en/arduino/arduino_development)
  - See sample flashing command-line after configuring Arduino and trying to flash sample program (w/o sudo or udev setup for USB device)
- Try to retrofit cmdline

I then connected to the ATOM device (end-effector); via `dmesg -w`, it was listed on `/dev/ttyUSB0`. I then tried to flash it extrapolating from what the Arduino IDE attempted:

```sh
sudo python -B ~/.arduino15/packages/m5stack/tools/esptool_py/3.0.0/esptool.py \
    --chip esp32 \
    --port /dev/ttyUSB0 \
    --baud 1500000 \
    --before default_reset \
    --after hard_reset \
    write_flash \
    -z \
    --flash_mode qio \
    --flash_freq 80m \
    --flash_size detect \
    0xe000 ~/Downloads/myStudio_2.2/ino/boot_app0.bin \
    0x1000 ~/Downloads/myStudio_2.2/ino/bootloader_qio_80m.bin \
    0x10000 ~/Downloads/myStudio_2.2/ino/myCobot/atom/AtomMain-2.8.ino.bin \
    0x8000 ~/Downloads/myStudio_2.2/ino/myCobot/atom/AtomMain-2.8.ino.partitions.bin
```

However, that didn't work. Can I ask what I am doing wrong here?

**Comment by eacousineau** [comment]
for C

**Comment by eacousineau** [comment]
Also tried compiling `MainControl.ino` via Arduino (plugged into base), but seemed to have bricked my arm:

```sh
sudo python -B ~/.arduino15/packages/m5stack/tools/esptool_py/3.0.0/esptool.py \
    --chip esp32 \
    --port /dev/ttyUSB0 \
    --baud 921600 \
    --before default_reset \
    --after hard_reset \
    write_flash \
    -z \
    --flash_mode qio \
    --flash_freq 80m \
    --flash_size detect \
    0xe000 ~/.arduino15/packages/m5stack/hardware/esp32/1.0.7/tools/partitions/boot_app0.bin \
    0x1000 ~/.arduino15/packages/m5stack/hardware/esp32/1.0.7/tools/sdk/bin/bootloader_qio_80m.bin \
    0x10000 /tmp/arduino_build_977973/MainControl.ino.bin \
    0x8000 /tmp/arduino_build_977973/MainControl.ino.partitions.bin
```

Used this program, but had to prepend the following (after configuring include libraries) to get it to compile (which I believe is in line with the `fonts.png` suggestion)
https://github.com/elephantrobotics/myCobot/blob/3d6c2c488/Arduino/MycobotBasic/examples/MainControl/MainControl.ino
```
#define LOAD_GFXFF 1
#define USE_M5_FONT_CREATOR 1
#include <Fonts/GFXFF/gfxfont.h>
```

**Comment by zlj-zz** [comment]
You can refer to this [https://github.com/zlj-zz/minimycobotflasher](https://github.com/zlj-zz/minimycobotflasher)

**Comment by eacousineau** [comment]
That worked beautifully, thank you!

If it's at all helpful, I've filed some minor PRs:
https://github.com/zlj-zz/minimycobotflasher/pull/2
https://github.com/zlj-zz/minimycobotflasher/pull/3
