### ISSUE TITLE
Failed to write minirobot firmware v1.0

### ISSUE THREAD

**Issue by 3110** [elephantrobotics/myStudio#13]
When I select minorobot v1.0 and push "Download," myStudio v2.2 downloads minirobot-1.0.ino.bin, minirobot-1.0.ino.partitions.bin, and the unnecessary minirobot-0.4.ino.bin.  This unnecessary file causes myStudio to misunderstand in detecting the firmware version, so myStudio tries to write minirobot firmware v0.4 instead of v1.0.

If you remove minirobot-0.4.ino.bin from the folder ino/myCobot/basic, you can succeed in writing the minirobot v1.0 firmware.

**Comment by Eheech** [comment]
Thank you for your feedback, this bug had been fixed. Thank you very much .
