### ISSUE TITLE
MacOS: Mystudio is damaged and can't be opened. 

### ISSUE THREAD

**Issue by mfkenson** [elephantrobotics/myStudio#14]
Mystudio-3.0.0.dmg
<img width="254" alt="Screenshot 2021-07-29 at 6 48 57 PM" src="https://user-images.githubusercontent.com/1910865/127479222-91d880b0-c40b-4442-847a-cb53e46192e7.png">

<img width="270" alt="Screenshot 2021-07-29 at 6 50 29 PM" src="https://user-images.githubusercontent.com/1910865/127479345-3cf89fb4-cecc-400d-84fa-8025114d6182.png">

**Comment by xcqy** [comment]
`sudo spctl --master-disable`
You can use this command to trust the software
and try again
