### ISSUE TITLE
Wrong text in Japanese

### ISSUE THREAD

**Issue by 3110** [elephantrobotics/myStudio#16]
Version: myStudio v3.2.1, v3.2.3

- Unnecessary kana pronouncing is displayed before Chinese characters
- Wrong translation for the Type
- "Japanese"  in the Language field is displayed in Chinese

[![Image from Gyazo](https://i.gyazo.com/603eb9622a5146cfaeb9c414c4d63c22.png)](https://gyazo.com/603eb9622a5146cfaeb9c414c4d63c22)

**Comment by LoveCodingOnGithub** [comment]
@3110

**Comment by LoveCodingOnGithub** [comment]
@3110  OK , I got it . I will fix it next version
