### ISSUE TITLE
myStudio 3.2.3  - no binary release for Linux x86_64

### ISSUE THREAD

**Issue by jalapenopuzzle** [elephantrobotics/myStudio#17]
* myStudio git repository has no source code
* No appimage for x86_64.

**Comment by alebarra** [comment]
> * myStudio git repository has no source code
> 
>     * No appimage for x86_64.

I agree with the request, there is no support for amd64 yet

**Comment by anla-xu** [comment]
[Support Linux amd64](https://github.com/elephantrobotics/myStudio/releases/tag/v3.6.1)

**Comment by apockill** [comment]
Awesome, thank you @anla-xu !
