### ISSUE TITLE
myStudio can't boot on macOS Big Sur(Version 11.0.1)

### ISSUE THREAD

**Issue by karaage0703** [elephantrobotics/myStudio#2]
myStudio(V0.02, V0.04) can't boot on macOS Big Sur(11.0.1)

NG:
- macOS Big Sur(11.0.1)
- iMac (Retina 4K, 21.5-inch, 2017)
- Intel Core i7

macOS Mojave is no problem.

OK:
- macOS Mojave(10.14.5)
- MacBook Pro(Retina, Mid 2012)
- Intel Core i7

I'm happy if I can use myStudio on macOS Big Sur.

**Comment by zlj-zz** [comment]
ok, I got it. Please wait.

**Comment by flamby** [comment]
Hello,

No MacOS edition for myStudio 0.05, and 0.04 is not working on Big Sur as already reported.

When can we expect a working myStudio for mac?

**Comment by zlj-zz** [comment]
It's in our plan, and when the holidays are over, we'll start working on it.

**Comment by flamby** [comment]
Same issue with 1.0...
