### ISSUE TITLE
myStudio的linux安装包在ubuntu20.04无法运行

### ISSUE THREAD

**Issue by wojiaoCRG** [elephantrobotics/myStudio#21]
1、添加了权限和libfuse 2，双击没用，运行程序打开光标会转，但没有打开，用终端命令报以下错误。
crg@crg-VirtualBox:~/桌面$ ./myStudio-latest.AppImage
bash: ./myStudio-latest.AppImage：无法执行二进制文件: 可执行文件格式错误

**Comment by apockill** [comment]
This issue is a duplicate of https://github.com/elephantrobotics/myStudio/issues/22

**Comment by anla-xu** [comment]
[Support Linux amd64](https://github.com/elephantrobotics/myStudio/releases/tag/v3.6.1)
