### ISSUE TITLE
MyStudio安装包在ubuntu22.04无法安装

### ISSUE THREAD

**Issue by winster-bai** [elephantrobotics/myStudio#22]
./myStudio-latest.AppImage 
bash: ./myStudio-latest.AppImage: 无法执行二进制文件：可执行文件格式错误

另外，你家官网客服真的态度很差

**Comment by y-z-g** [comment]
Same issue

**Comment by apockill** [comment]
I am also having this issue. Is this because the binary is only compiled for ARM64?

**Comment by anla-xu** [comment]
[Support Linux amd64](https://github.com/elephantrobotics/myStudio/releases/tag/v3.6.1)
