### ISSUE TITLE
myStudio can not flash M5Stack Base with the latest image.

### ISSUE THREAD

**Issue by nisshan-x** [elephantrobotics/myStudio#3]
myStudio can not flash M5Stack Base with the latest image.

myStudio v.0.0.4
PC
 - macOS Catalina 10.15.7
 - Windows10

By the way, M5Atom flash finished successfully.

**Comment by zlj-zz** [comment]
What's your mean?

**Comment by nisshan-x** [comment]
Take a look at attached screenshots.

<img width="1026" alt="スクリーンショット 2021-01-28 17 56 59" src="https://user-images.githubusercontent.com/67353276/106114088-876b2e80-6192-11eb-8d15-eea8e7a8c051.png">
<img width="1030" alt="スクリーンショット 2021-01-28 17 57 55" src="https://user-images.githubusercontent.com/67353276/106114112-90f49680-6192-11eb-8e95-10f1fc3ffd8d.png">

**Comment by xcqy** [comment]
Windows10 also can't flash?

**Comment by nisshan-x** [comment]
Windows10 also can't flash.

**Comment by nisshan-x** [comment]
@xcqy 
Why do  you close this issue without any solution? I need your help.

**Comment by xcqy** [comment]
Oh, my mistake, it's the same error as macOS ？

**Comment by nisshan-x** [comment]
Yes, errors in both OS are the same.

**Comment by zlj-zz** [comment]
What is your Mac system? Currently, it can't run on Big Sur and M1

**Comment by nisshan-x** [comment]
macOS Catalina 10.15.7

**Comment by zlj-zz** [comment]
Are other functions normal? Only flash is not allowed?
We are looking into the problem,but our computers are running well, so it takes time and as much information as possible.

**Comment by nisshan-x** [comment]
Ok. I will try another functions later.

**Comment by nisshan-x** [comment]
myCobot v 0.0.4 on macOS Catalina 10.15.7, connected with Basic:

MainControl -> failed
myCobotBLE -> failed
Transponder -> failed
Calibration -> failed
MainControl_test0.0.2 -> failed
myCobotBLE_test0.0.2 -> failed

pymycobot on Ubuntu 18.04:
 get_angles() -> OK
 get_radians() -> OK

**Comment by zlj-zz** [comment]
OK, we'll try to find out.
If mystudio works well on Ubuntu, please use it on Ubuntu first.
