### ISSUE TITLE
Can't run myStudio on Ubuntu 18.04

### ISSUE THREAD

**Issue by nisshan-x** [elephantrobotics/myStudio#4]
I downloaded and decompressed MyStudio-linux.tar.xz
 (v0.0.4), and tried to start myStudio on Ubuntu 18.04, but failed with the following error:

```
$ ./MyStudio 
[39600] Error loading Python lib '/home/xxx/MyStudio-linux/MyStudio/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/xxx/MyStudio-linux/MyStudio/libpython3.8.so.1.0)
```

I checked GLIBC on my Ubuntu:
```
$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.3) 2.27
```

So, what version of Ubuntu is required to run myStudio? 16.04?

I'd like you to write system requirements on readme.

**Comment by nisshan-x** [comment]
I tried to start myStudio on Ubuntu 16.04, but failed too:

```
$ ./MyStudio 
[51326] Error loading Python lib '/home/xxx/MyStudio_v0.0.4/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/xxx/MyStudio_v0.0.4/libpython3.8.so.1.0)
```

```
$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.2) 2.23
```

Please take a look.

Thanks.

**Comment by nisshan-x** [comment]
It's OK with Ubuntu 20.04. myStudio started up successfully.

So what linux OS is required?

**Comment by zlj-zz** [comment]
That's a good question.
We tested it on Ubuntu 16.04 and Ubuntu 20.4, and it's OK.
We hope it will work well on most Linux, and we will continue to repair and improve it.
Thank you for your feedback.

**Comment by fedorenchik** [comment]
@nisshan-x We have reuploaded linux version. Should work on Ubuntu 16.04+. Please try it.

**Comment by cpilon** [comment]
I have the same issue on Ubuntu 18.04...is there any solution?

**Comment by apockill** [comment]
This is an issue with Pyinstalled linux binaries.

@fedorenchik if you open source this (or give me source access), I can help you by making a [Snap](https://snapcraft.io/) for you, which would work on all linux distributions.

**Comment by xcqy** [comment]
@cpilon Which version of mystudio are you using

**Comment by xcqy** [comment]
The latest version can run on Ubuntu 16.04 +
