### ISSUE TITLE
ATOM stops processing commands for tens of seconds after invoking set_gripper_state(1, speed)

### ISSUE THREAD

**Issue by 3110** [elephantrobotics/myStudio#5]
Firmware: AtomMain 2.5
pymycobot: 2.2.0

When invoking set_gripper_state(1, speed), ATOM stops processing commands and locks the adaptive gripper for about 40 seconds.

**Comment by zlj-zz** [comment]
So what's the problem? too slow?

**Comment by 3110** [comment]
Is this calibration problem?  I want to open and close the gripper quickly with set_gripper_state(1, speed) and set_gripper_state(0, speed).  How can I avoid locking the gripper?

**Comment by zlj-zz** [comment]
What is the type of your gripper?

**Comment by 3110** [comment]
My gripper is [MyCobot Adaptive Gripper](https://shop.elephantrobotics.com/products/mycobot-adaptive-gripper?variant=33483975557206)

**Comment by zlj-zz** [comment]
You can try to turn off the power and open the gripper to the maximum. 
Then initialize at that location and continue trying.

Initialization using `set_gripper_ini()`

```
set_gripper_ini()

    Description

    Set the current position to zero

    Current position value is 248.

```

**Comment by 3110** [comment]
I try the following code with pymycobot 2.1.2 after opening the gripper to the maximum:

```
>>> from pymycobot.mycobot import MyCobot
>>> mycobot = MyCobot("COM11")
>>> mycobot.set_gripper_ini()
>>> mycobot.set_gripper_state(1, 50) # closing the gripper is OK, but the gripper gets stuck
>>> mycobot.set_gripper_state(0, 50) # the gripper doesn't move
```

**Comment by zlj-zz** [comment]
Did you initialize it? 
You need to initialize once when the gripper is maximum, just once. 
The initialization method is given above.

**Comment by 3110** [comment]
I finally understand how to initialize the gripper.

1. Turn off the power
2. Open the gripper to the maximum
3. Turn on the power
4. Connect MyCobot and call set_gripper_ini() to initialize the gripper
5. Turn off the power and turn on the power
6. Connect MyCobot, then call set_gripper_state(1, 50) and set_gripper_state(0, 50) -> OK

Is this right ?

**Comment by zlj-zz** [comment]
That's right. 
But you don't have to go to the fifth step. After initialization, you can use it directly.

**Comment by 3110** [comment]
Thanks you !
