### ISSUE TITLE
myStudio v1.0 for macOS is not responding

### ISSUE THREAD

**Issue by jamesgarriss** [elephantrobotics/myStudio#7]
I used AppCleaner to uninstall the previous version, downloaded the v1.0 dmg file from releases, double-clicked to install, dragged the app to Applications, and started it.  I used Security & Privacy to allow the app to start.  Although the app starts, no windows are displayed.  When I right-click the app icon, it says that it is "not responding".  I deleted the app, restarted, and did everything again, but I got the same response.  Note that this happens whether I am connected to myCobot via USB cable or not.   v1.0 does not appear to be working.

Question:  Does this version work with macOS v11 (Big Sur)?  The previous version that I had working was before I upgraded to Big Sur.

**Comment by zlj-zz** [comment]
we dont have mac with big sur. so maybe we cant support this version. sorry
