### ISSUE TITLE
Will this be open sourced?

### ISSUE THREAD

**Issue by apockill** [elephantrobotics/myStudio#8]
Hi, I'm curious what portions of the myCobot stack will remain close sourced. 

If it's open sourced, I'm happy to apply my PyQT5/python experience to help crush bugs. I can also assist in fixing mistranslated english across the software.

Cheers!

**Comment by eacousineau** [comment]
For those looking to simply flash the firmware with a less proprietary process, see:
https://github.com/zlj-zz/minimycobotflasher (mentioned in #10)
